import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Simon David</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Simon David's Project
        </h1>


        <div className={styles.grid}>

         
          <a href="/questions/first" className={styles.card}>
         <div>
          <h1>
          Question 1 : 
          </h1>
          <p> Things a Product Advocate Might Do:</p>
          </div>
          </a>

          <a href="/questions/second" className={styles.card}>
         <div>
          <h1>
          Question 2 : 
          </h1>
          <p> Reflection on past experience</p>
          </div>
          </a>

          <a href="/questions/third" className={styles.card}>
         <div>
          <h1>
          Question 3 : 
          </h1>
          <p> Practice Email Responses</p>
          </div>
          </a>

          <a href="/questions/fourth" className={styles.card}>
         <div>
          <h1>
          Question 4 : 
          </h1>
          <p> Your personal recommendations:</p>
          </div>
          </a>
          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
